# Generated by Django 3.1.2 on 2020-12-06 12:00

from django.db import migrations, models
import django.db.models.deletion
import utils.models.non_polymorphic_cascade


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0005_volume_vol_id'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeNotification',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.notification')),
                ('actor', models.ForeignKey(on_delete=utils.models.non_polymorphic_cascade.NON_POLYMORPHIC_CASCADE, related_name='notifications', to='instances.volume')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.notification',),
        ),
        migrations.CreateModel(
            name='VolumeFailedNotification',
            fields=[
                ('volumenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.volumenotification')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.volumenotification',),
        ),
        migrations.CreateModel(
            name='VolumeFinishedNotification',
            fields=[
                ('volumenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.volumenotification')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.volumenotification',),
        ),
        migrations.CreateModel(
            name='VolumeScheduledNotification',
            fields=[
                ('volumenotification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notifications.volumenotification')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('notifications.volumenotification',),
        ),
    ]
