# Generated by Django 3.0.8 on 2020-09-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imageUrl',
            new_name='image_url',
        ),
    ]
