# Generated by Django 3.0.8 on 2020-09-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instance',
            options={'permissions': (('access_instance', 'Access instance'),)},
        ),
    ]
