# Generated by Django 3.1.2 on 2020-12-05 19:02

from django.db import migrations, models
import utils.mixins.access


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0002_auto_20200928_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'permissions': (('access_volume', 'Access volumes'),),
            },
            bases=(models.Model, utils.mixins.access.AccessMixin),
        ),
    ]
