# Generated by Django 3.1.2 on 2020-12-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0003_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='volumes',
            field=models.ManyToManyField(related_name='instances', to='instances.Volume'),
        ),
    ]
