# Generated by Django 3.1.2 on 2020-12-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instances', '0004_instance_volumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='vol_id',
            field=models.TextField(null=True),
        ),
    ]
