# Generated by Django 3.0.8 on 2020-07-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200719_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='no_avatar', upload_to='avatars'),
        ),
    ]
