name: scripts

on:
  push:
    paths:
      - 'scripts/**'
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install flake8
      run: |
        pip install flake8

    - name: Run flake8
      run: flake8 scripts/

  type-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install mypy
      run: pip install mypy

    - name: Run mypy
      run: mypy scripts/